// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSK_MZXogXbdFxWAKSwR5i4Ke0zWMzLg',
    appId: '1:242098252037:web:b4da1e1a92e7a7970fef6c',
    messagingSenderId: '242098252037',
    projectId: 'smart-quiz-acd6b',
    authDomain: 'smart-quiz-acd6b.firebaseapp.com',
    storageBucket: 'smart-quiz-acd6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEEa0YWYdhxSgtMj4_Ct1XmfpBBUQEjvQ',
    appId: '1:242098252037:android:ea37e33a7238927e0fef6c',
    messagingSenderId: '242098252037',
    projectId: 'smart-quiz-acd6b',
    storageBucket: 'smart-quiz-acd6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt7jPV5DaVoK3BgGDK9YjlgWAe00zzx70',
    appId: '1:242098252037:ios:ba5de646727fe5ce0fef6c',
    messagingSenderId: '242098252037',
    projectId: 'smart-quiz-acd6b',
    storageBucket: 'smart-quiz-acd6b.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt7jPV5DaVoK3BgGDK9YjlgWAe00zzx70',
    appId: '1:242098252037:ios:ba5de646727fe5ce0fef6c',
    messagingSenderId: '242098252037',
    projectId: 'smart-quiz-acd6b',
    storageBucket: 'smart-quiz-acd6b.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHSK_MZXogXbdFxWAKSwR5i4Ke0zWMzLg',
    appId: '1:242098252037:web:c3c009d770f571ee0fef6c',
    messagingSenderId: '242098252037',
    projectId: 'smart-quiz-acd6b',
    authDomain: 'smart-quiz-acd6b.firebaseapp.com',
    storageBucket: 'smart-quiz-acd6b.firebasestorage.app',
  );
}
